stages:
    - docker-building
    - configure
    - compile-lib
    - compile-bin
    - test
    - documentation

build_docker_env:
    stage: docker-building
    image: docker:git
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN molimen1.dcci.unipi.it:22003
        - docker build -t molimen1.dcci.unipi.it:22003/molecolab/open-mmpol .
        - docker push molimen1.dcci.unipi.it:22003/molecolab/open-mmpol
    only:
        refs:
            - pushes
        changes:
            - Dockerfile

cmake-config:
    stage: configure
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=DEBUG ..
    artifacts:
        paths:
            - build

cmake-config-intel:
    stage: configure
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - mkdir build_intel
        - cd build_intel
        - CC=/opt/intel/oneapi/compiler/latest/linux/bin/intel64/icc 
          CXX=/opt/intel/oneapi/compiler/latest/linux/bin/intel64/icc 
          FC=/opt/intel/oneapi/compiler/latest/linux/bin/intel64/ifort 
          cmake -DCMAKE_BUILD_TYPE=DEBUG ..
    artifacts:
        paths:
            - build_intel

make-lib:
    stage: compile-lib
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make openmmpol
    artifacts:
        paths:
            - build
    only:
        - pushes

compile-C:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make C_test_init C_test_ipd C_test_energy C_test_init_xyz C_test_potential_xyz
    artifacts:
        paths:
            - build/bin/C_test_init
            - build/bin/C_test_ipd
            - build/bin/C_test_energy
            - build/bin/C_test_init_xyz
            - build/bin/C_test_potential_xyz
    only:
        - pushes

compile-FORTRAN:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make F_test_init
    artifacts:
        paths:
            - bin/F_test_init
    only:
        - pushes

make-lib-intel:
    stage: compile-lib
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - cd build_intel
        - make openmmpol
    artifacts:
        paths:
            - build_intel
    only:
        - pushes

compile-C-intel:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - cd build_intel
        - make C_test_init C_test_ipd C_test_energy C_test_init_xyz C_test_potential_xyz
    artifacts:
        paths:
            - build_intel/bin/C_test_init
            - build_intel/bin/C_test_ipd
            - build_intel/bin/C_test_energy
            - build_intel/bin/C_test_init_xyz
            - build_intel/bin/C_test_potential_xyz
    only:
        - pushes

compile-FORTRAN-intel:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - cd build_intel
        - make F_test_init
    artifacts:
        paths:
            - build_intel/bin/F_test_init
    only:
        - pushes

make-doc:
    stage: documentation
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - ford DOC.md 
    artifacts:
        paths:
            - doc
    only:
        - pushes

run_tests:
    stage: test
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make test
    only:
        - pushes

run_tests-intel:
    stage: test
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - cd build_intel
        - make test
    only:
        - pushes
