stages:
    - docker-building
    - configure
    - compile-lib
    - compile-bin
    - test
    - documentation

build_docker_env:
    stage: docker-building
    image: docker:git
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN molimen1.dcci.unipi.it:22003
        - docker build -t molimen1.dcci.unipi.it:22003/molecolab/open-mmpol .
        - docker push molimen1.dcci.unipi.it:22003/molecolab/open-mmpol
    only:
        refs:
            - pushes
        changes:
            - Dockerfile

cmake-config:
    stage: configure
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=DEBUG ..
    artifacts:
        paths:
            - build

cmake-config-intel:
    stage: configure
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - mkdir build_intel
        - cd build_intel
        - CC=/opt/intel/oneapi/compiler/latest/linux/bin/intel64/icc 
          CXX=/opt/intel/oneapi/compiler/latest/linux/bin/intel64/icc 
          FC=/opt/intel/oneapi/compiler/latest/linux/bin/intel64/ifort 
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DHDF5_ROOT=/opt/intel/hdf5-1.12.2 ..
    artifacts:
        paths:
            - build_intel

cmake-config-nvidia:
    stage: configure
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - export NVARCH=`uname -s`_`uname -m`
        - export NVCOMPILERS=/opt/nvidia/hpc_sdk
        - export PATH=$NVCOMPILERS/$NVARCH/2022/compilers/bin:$PATH
    script:
        - mkdir build_nvidia
        - cd build_nvidia
        - CC=`which nvc` 
          CXX=`which nvcc`
          FC=`which nvfortran`
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DHDF5_ROOT=/opt/nvidia/hdf5-1.12.2 ..
    artifacts:
        paths:
            - build_nvidia

make-lib:
    stage: compile-lib
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make openmmpol
    artifacts:
        paths:
            - build
    only:
        - pushes
        - schedules

compile-C:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make C_test_init C_test_ipd C_test_energy C_test_init_xyz C_test_potential_xyz ommp_pp  C_test_potential_hdf5 C_test_init_hdf5 C_test_geomgrad
    artifacts:
        paths:
            - build/bin
    only:
        - pushes
        - schedules

compile-FORTRAN:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make F03_test_init F03_test_ipd F03_test_energy F03_test_init_xyz F03_test_potential_xyz F03_test_geomgrad
    artifacts:
        paths:
            - build/bin
    only:
        - pushes
        - schedules

make-lib-intel:
    stage: compile-lib
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - cd build_intel
        - make openmmpol
    artifacts:
        paths:
            - build_intel
    only:
        - schedules

compile-C-intel:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - cd build_intel
        - make C_test_init C_test_ipd C_test_energy C_test_init_xyz C_test_potential_xyz ommp_pp  C_test_potential_hdf5 C_test_init_hdf5 C_test_geomgrad
    artifacts:
        paths:
            - build_intel/bin
    only:
        - schedules

compile-FORTRAN-intel:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - cd build_intel
        - make F03_test_init F03_test_ipd F03_test_energy F03_test_init_xyz F03_test_potential_xyz F03_test_geomgrad
    artifacts:
        paths:
            - build_intel/bin
    only:
        - schedules

make-lib-nvidia:
    stage: compile-lib
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - export NVARCH=`uname -s`_`uname -m`
        - export NVCOMPILERS=/opt/nvidia/hpc_sdk
        - export PATH=$NVCOMPILERS/$NVARCH/2022/compilers/bin:$PATH
    script:
        - cd build_nvidia
        - make openmmpol
    artifacts:
        paths:
            - build_nvidia
    only:
        - schedules

compile-C-nvidia:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - export NVARCH=`uname -s`_`uname -m`
        - export NVCOMPILERS=/opt/nvidia/hpc_sdk
        - export PATH=$NVCOMPILERS/$NVARCH/2022/compilers/bin:$PATH
    script:
        - cd build_nvidia
        - make C_test_init C_test_ipd C_test_energy C_test_init_xyz C_test_potential_xyz ommp_pp  C_test_potential_hdf5 C_test_init_hdf5 C_test_geomgrad
    artifacts:
        paths:
            - build_nvidia/bin
    only:
        - schedules

compile-FORTRAN-nvidia:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - export NVARCH=`uname -s`_`uname -m`
        - export NVCOMPILERS=/opt/nvidia/hpc_sdk
        - export PATH=$NVCOMPILERS/$NVARCH/2022/compilers/bin:$PATH
    script:
        - cd build_nvidia
        - make F03_test_init F03_test_ipd F03_test_energy F03_test_init_xyz F03_test_potential_xyz F03_test_geomgrad
    artifacts:
        paths:
            - build_nvidia/bin
    only:
        - schedules

make-doc:
    stage: documentation
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - ford DOC.md 
    artifacts:
        paths:
            - doc
    only:
        - pushes

run_short_test:
    stage: test
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - ctest -R 'NMA|1crn|2d94' -E memcheck
    only:
        - pushes

run_tests:
    stage: test
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make test
    only:
        - schedules

run_tests-intel:
    stage: test
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - source /opt/intel/oneapi/setvars.sh
    script:
        - cd build_intel
        - make test
    only:
        - schedules

run_tests-nvidia:
    stage: test
    image: $CI_REGISTRY_IMAGE:latest
    before_script:
        - export FORTRANOPT=no_minus_zero
    script:
        - cd build_nvidia
        - ctest -E memcheck
    only:
        - schedules
