stages:
    - docker-building
    - compile-lib
    - compile-bin

build_docker_env:
    stage: docker-building
    image: docker:git
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN molimen1.dcci.unipi.it:22003
        - docker build -t molimen1.dcci.unipi.it:22003/molecolab/open-mmpol .
        - docker push molimen1.dcci.unipi.it:22003/molecolab/open-mmpol
    only:
        refs:
            - pushes
        changes:
            - Dockerfile

make-lib:
    stage: compile-lib
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - make libraries
    artifacts:
        paths:
            - lib/libopenmmpol.so
    only:
        - pushes

compile-C:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - make C_binaries
    artifacts:
        paths:
            - bin/*.out
    only:
        - pushes

compile-FORTRAN:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - make FORTRAN_binaries
    artifacts:
        paths:
            - bin/*.exe
    only:
        - pushes
