stages:
    - docker-building
    - configure
    - compile-lib
    - compile-bin
    - documentation

build_docker_env:
    stage: docker-building
    image: docker:git
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN molimen1.dcci.unipi.it:22003
        - docker build -t molimen1.dcci.unipi.it:22003/molecolab/open-mmpol .
        - docker push molimen1.dcci.unipi.it:22003/molecolab/open-mmpol
    only:
        refs:
            - pushes
        changes:
            - Dockerfile

cmake-config:
    stage: configure
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=DEBUG ..
    artifacts:
        paths:
            - build

make-lib:
    stage: compile-lib
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make openmmpol
    artifacts:
        paths:
            - build
    only:
        - pushes

compile-C:
    stage: compile-bin
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - cd build
        - make test_c
    artifacts:
        paths:
            - build/bin/test_c
    only:
        - pushes

make-doc:
    stage: documentation
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - ford DOC.md 
    artifacts:
        paths:
            - doc
    only:
        -pushes

#compile-FORTRAN:
#    stage: compile-bin
#    image: $CI_REGISTRY_IMAGE:latest
#    script:
#        - make FORTRAN_binaries
#    artifacts:
#        paths:
#            - bin/*.exe
#    only:
#        - pushes
